[package]
name = "frost_test"
version = "0.1.0"
edition = "2024"

[dependencies]
frost-secp256k1-tr = { git = "https://github.com/conduition/frost.git", rev = "d580241e8561ed145a464e6671a511d5a8c218f8" }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
